// Generated from error-codes.json — do not edit manually
export const ErrorCode = {
  DATA_PARSE_ERROR: "DATA_PARSE_ERROR",
  INSTANCE_NOT_FOUND: "INSTANCE_NOT_FOUND",
  INSTANCE_SHUT_DOWN: "INSTANCE_SHUT_DOWN",
  NATIVE_MODULE_NOT_REGISTERED: "NATIVE_MODULE_NOT_REGISTERED",
  PRISM_NATIVE_ERROR: "PRISM_NATIVE_ERROR",
  TEALIUM_CANCELLED: "TEALIUM_CANCELLED",
} as const;
