# Risk Assessment for Pull Requests
# Specify risky file entries and associated reasons.
# View the following documentation for more information on usage and configuration:
# https://tealium.atlassian.net/wiki/x/DYAZPgE

name: pr-risk-analysis
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check-pr-risk:
    uses: Tealium/github-actions-shared/.github/workflows/ci-pr-risk.yml@main
    with:
      risk-entries: |
